name: "build plugin"
on:
  push:
    paths:
      - "build.gradle.kts"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Build Mirai Plugin
        run: ./gradlew buildPlugin

      - name: Upload Mirai Plugin
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ github.run_id }}
          path: build/mirai/*